title: Devin Beck's Website
email: Devin6Beck@gmail.com
description: >-
  Devin Beck's personal website.
baseurl: ""
url: "https://devinbeck.com"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
